In [53]:
import tensorflow as tf
import numpy as np

In [54]:
#numpy para creacion de arrays
numeros = [1,2,3,4]
print(type(numeros))

<class 'list'>


In [55]:
#Para crear el arreglo
array = np.array(numeros)
print(type(array))

<class 'numpy.ndarray'>


In [56]:
array

array([1, 2, 3, 4])

In [57]:
#con numpy puedo crear numeros
np.arange(0, 10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
#Para crear rango de numeros
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#array solo de 0
np.zeros(5)

In [ ]:
#array solo de dos
np.ones(5)

In [ ]:
#array de dimensiones 3 filas por 2 columnas
np.ones((3,2))

In [ ]:
#numeros aleatorios, linespace desde el 0 al 40, dame 10 numeros
np.linspace(0, 40, 10)

In [ ]:
#El tercer argumento es la cantidad de numeros que obtenemos dentro de ese rango
np.random.randint(0,100, 10)

In [35]:
#a partir de un array podemos saber el maximo, minimo, mediana....
array = np.random.randint(0,100, 10)
print(array)
array.max() 


[72 30 13 35 37 29  3 97 33 83]


97

In [36]:
#en que lugar esta el maximo
array.argmax()

7

In [ ]:
#Para calcular la mediana
array.mean()

In [41]:
#Para poner mas filas a un array, con reshape, podemos poner 5 filas con 2 columnas
print(array)
array.reshape(5,2)


[72 30 13 35 37 29  3 97 33 83]


array([[72, 30],
       [13, 35],
       [37, 29],
       [ 3, 97],
       [33, 83]])

In [48]:
#Filtrar elementos de un array
array = array.reshape(5,2)
array


array([[72, 30],
       [13, 35],
       [37, 29],
       [ 3, 97],
       [33, 83]])

In [52]:
filtro = array > 30
array2 = array[filtro]
array2

array([72, 35, 37, 97, 33, 83])